on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: build and publish to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: install, test cli
        run: |
          pip3 install .
          python3 -m gwh --help

      - name: install dependencies & build
        run: |
          pip3 install build
          python3 -m build

      - name: publish to PyPi
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
